version: "3"
services:
  kroki:
    image: yuzutech/kroki
    depends_on:
      - excalidraw
    environment:
      - KROKI_EXCALIDRAW_HOST=excalidraw
    ports:
      - "8080:8000"
  excalidraw:
    image: yuzutech/kroki-excalidraw
    expose:
      - "8004"